# set the board to uno because nano has incorrect fuses for new bootloader
ARDUINO_DIR = /home/stelian/Arduino/arduino-1.8.19/
BOARD_TAG = uno
BOARD_SUB = atmega328p

ISP_PROG = avrispmkii

include $(ARDUINO_DIR)/Arduino.mk
