ARDUINO_DIR = /home/stelian/Arduino/arduino-1.8.18/
BOARD_TAG = pro
BOARD_SUB = 8MHzatmega328

CPPFLAGS = -I.
ARDUINO_LIBS = IRLib2 IRLibProtocols IRLibRecvPCI
USER_LIB_PATH = $(realpath IRLib2)

ISP_PROG = avrispmkii

ARDMK_DIR = /home/stelian/Arduino/arduino-1.8.18/
include Arduino-noserial.mk
